### ISSUE TITLE
Display the data provenance

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/overture#6]
Declare the source institution of the data displayed on a page.

**Comment by rtroncy** [comment]
This is a sensitive marketing issue. What we agreed on: 
* On the general layout and therefore applicable to ALL pages: display the 3 logos of our partner institutions since we are visualizing DOREMUS, the sum of the 5 DBs
* On each (expression) page, find a way to display where the data comes from (perhaps, showing a simple property / value rather than a logo)
